### ISSUE TITLE
Any plan to provide a det-based CoTTA baseline?

### ISSUE THREAD

**Issue by zehuichen123** [zwbx/SHIFT-Continuous_Test_Time_Adaptation#1]
hi, thanks for your great work! Do you have plans to provide a cotta baseline for detection?

**Comment by zwbx** [comment]
Sorry, we do not have the plan yet.Sent from my iPhoneOn 21 Jun 2023, at 3:48 pm, loveSnowBest ***@***.***> wrote:﻿
hi, thanks for your great work! Do you have plans to provide a cotta baseline for detection?

**Comment by zehuichen123** [comment]
Thanks for your reply~
