### ISSUE TITLE
Usage of other pretrained model in ICCV2023 Workshop Challenge

### ISSUE THREAD

**Issue by HRHLALALA** [zwbx/SHIFT-Continuous_Test_Time_Adaptation#3]
Hi, I want to double check whether it is allowed to use different pretrained model to perform the TTA?

**Comment by zwbx** [comment]
yes. it is permitted, but additional dataset is forbidden.

**Comment by zwbx** [comment]
refer to another [repo](https://github.com/zwbx/SHIFT-TTA-train_source_model)  for your own pretrained source model.
