### ISSUE TITLE
Test batch size

### ISSUE THREAD

**Issue by dmn-sjk** [zwbx/SHIFT-Continuous_Test_Time_Adaptation#5]
Question regarding the challenge: Are we allowed to modify the batch size for TTA testing?

**Comment by zwbx** [comment]
The model is designed to process sequential inputs. In this context, it means that when predicting semantic segmentation results for a given time frame (t), the model does not have access to any frame later than time t. This ensures that the predictions are made solely based on the information up to the current time step and no future data is being used. This restriction is important in many real-time applications where future data is not available at the time of prediction.

For most existing methods, the batch size is one. However, we have not specified a fixed batch size and it is allows you matain a window or memory bank of history inputs.
________________________________
发件人: Damian Sójka ***@***.***>
发送时间: 2023年7月11日 0:54
收件人: zwbx/SHIFT-Continuous_Test_Time_Adaptation ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zwbx/SHIFT-Continuous_Test_Time_Adaptation] Test batch size (Issue #5)


CAUTION: External email. Only click on links or open attachments from trusted senders.

________________________________
Question regarding the challenge: Are we allowed to modify the batch size for TTA testing?
