### ISSUE TITLE
Can not find '/train/front/seq.csv'

### ISSUE THREAD

**Issue by JACK-Chen-2019** [zwbx/SHIFT-Continuous_Test_Time_Adaptation#6]
I have solvded this problem, thanks.

**Comment by zwbx** [comment]
Thanks for your quiry. We have update the command in the github page, or you can refer to shiftdataset website download page for it.
________________________________
发件人: JACK-Chen-2019 ***@***.***>
发送时间: 2023年7月14日 18:07
收件人: zwbx/SHIFT-Continuous_Test_Time_Adaptation ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zwbx/SHIFT-Continuous_Test_Time_Adaptation] Can not find '/train/front/seq.csv' (Issue #6)


CAUTION: External email. Only click on links or open attachments from trusted senders.

________________________________
When running
python download.py
--view "[front]" --group "[img, semseg]"
--split "[train, val, test]" --framerate "[videos]"
--shift "continuous/1x"
./data/shift
There is no /train/front/seq.csv in download root.
Thanks!
