### ISSUE TITLE
How to porcess the downloaded datasets?

### ISSUE THREAD

**Issue by yuyongcan** [zwbx/SHIFT-Continuous_Test_Time_Adaptation#7]
How to process the downloaded datasets using the command download.py. Unzip it to directory ./img and ./semseg seems it doesn't work. And it will report No such file or directory: './data/shift/continuous/videos/1x/val/front/img/b90a-c6c0'

**Comment by yuyongcan** [comment]
![image](https://github.com/zwbx/SHIFT-Continuous_Test_Time_Adaptation/assets/83764015/93d7c579-440e-46ca-96e6-73aa27add16c)
This is my directory structure after unzipping.

**Comment by fencingx** [comment]
I have the same problem. How did you solve this problem? Thanks
