### ISSUE TITLE
Problems of saving result for ICCV2023 Workshop

### ISSUE THREAD

**Issue by JACK-Chen-2019** [zwbx/SHIFT-Continuous_Test_Time_Adaptation#8]
I saved the "result" from the model prediction, and it seems that the pixel labels predicted by the model are different from the actual labels, which results in a significant difference between the results submitted in ICCV2023 Workshop and the results of local testing. Is there such a problem? How to solve it?

**Comment by JACK-Chen-2019** [comment]
It seems that target image has 23 classes, but the code can only predict 14 classes.

**Comment by zwbx** [comment]
The competition stipulates that the evaluation is conducted in 14 classes. For specific details, please refer to Segmentation labels in [https://www.vis.xyz/shift/get_started/](url)
