### ISSUE TITLE
Performance issue of Tent

### ISSUE THREAD

**Issue by Cascol-Chen** [zwbx/SHIFT-Continuous_Test_Time_Adaptation#9]
I find that Tent does not improve performance compared with source model, which contradicts to the paper in Figure 6. Could you further explain the difference?

**Comment by zwbx** [comment]
There may be some misunderstanding. This benchmark codebase is intended for the competition, not as an official repository for the original SHIFT paper. In our benchmark, there exist slight improvements comparing to baseline without any adaptation.
